version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend