services:
    backend:
	build: ./backend
        volumes:
	    - backend_volume:/backend
        ports:
	    - "8000:8000"

    streamlit_app:
	build: ./streamlit_app
        volumes:
    	    - backend_volume:/backend
            - streamlit_volume:/streamlit_app
	ports:
    	    - "8501:8501"
	depends_on:
    	    - backend

volumes:
    model_volume:
    streamlit_volume: